# Generated by Django 4.2 on 2023-06-22 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='wydatek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('kategoria', models.CharField(max_length=50)),
                ('kwota', models.FloatField()),
                ('data_powstania', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transakcja',
                'verbose_name_plural': 'transakcje',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='przychod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('kategoria', models.CharField(max_length=50)),
                ('kwota', models.FloatField()),
                ('data_powstania', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transakcja',
                'verbose_name_plural': 'transakcje',
                'abstract': False,
            },
        ),
    ]
