# Generated by Django 4.2 on 2023-06-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='przychod',
            options={'verbose_name': 'Przychod', 'verbose_name_plural': 'Przychody'},
        ),
        migrations.AlterModelOptions(
            name='wydatek',
            options={'verbose_name': 'Wydatek', 'verbose_name_plural': 'Wydatki'},
        ),
    ]
